- .github/workflows/sonar-scan.yml
- sonar-project.properties
[DCMAW-11483](https://govukverify.atlassian.net/browse/DCMAW-11483)
Added sonar scan workflow file as per these instructions: 
https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3668280149/How+to+integrate+GitHub+repositories+with+SonarCloud
---
<details>
* Is anything being logged that …
> DCMAW-11483: added sonar scan workflow and properties file

- .gitignore
- backend/Dockerfile
- backend/package.json
- backend/run-tests-locally.sh
- backend/run-tests.sh
- backend/template.yaml
- backend/test/api/basic.test.ts
> DCMAW-11525: Fix foundation setup

- backend/template.yaml
[DCMAW-11817](https://govukverify.atlassian.net/browse/DCMAW-11817)
Added StatusListTable setup logic in the `template.yaml` file
N/A
---
<details> …
> DCMAW-11817 Add StatusListTable setup

- backend/template.yaml
[DCMAW-11889](https://govukverify.atlassian.net/browse/DCMAW-11889)
Added the following resources for the Available Slots SQS Queue:
- encryption key
- key alias
- sqs queue
- queue policy
- dlq
---
<details>
* Does the code …
> DCMAW-11889: Set up AvailableSlots SQS Queue

- backend/README.md
- backend/template.yaml
[DCMAW-11896](https://govukverify.atlassian.net/browse/DCMAW-11896)
Added the following resources:
- TxMA SQS Queue
- DLQ
- SQS Queue Policy
- KMS Encryption Key
- KMS Key Alias
---
<details>
* Does the code conform to our …
> DCMAW-11896: TxMA SQS Queue

- .github/workflows/pull-request.yml
- .github/workflows/push-to-main.yml
- .gitignore
- backend/README.md
- backend/package-lock.json
- backend/package.json
- backend/registry.json
- backend/src/functions/issueStatusListEntryHandler.ts
- backend/template.yaml
- backend/test/unit/issueStatusListEntry/issueStatusListEntry.test.ts
[DCMAW-11887](https://govukverify.atlassian.net/browse/DCMAW-11887)
Added ClientRegistry bucket, as well as some initial policy configs
Test stack deployed and successfully added dummy file to bucket (with `aws s3 cp registry.json s3://mateis-stack-dev-status-list` CLI command)
N/A (?)
---
<details> …
> DCMAW-11887: Add ClientRegistry S3 bucket

- backend/mockListConfiguration.json
- backend/template.yaml
[DCMAW-13005](https://govukverify.atlassian.net/browse/DCMAW-13005)
Set up `ListConfiguration` bucket and populated it with some mock data to enable the development of the subsequent `FindAvailableSlots` lambda.
---
<details> …
> DCMAW-13005: Add ListConfiguration S3 bucket

- backend/template.yaml
[DCMAW-13035](https://govukverify.atlassian.net/browse/DCMAW-13035)
Added TokenStatusAvailableSlots SQS queue and adjusted naming for the corresponding BitstringAvailableSlots one
---
<details>
* Does the code conform to our …
> DCMAW-13035: Add TokenStatus SQS queue

- backend/mockClientRegistry.json
- backend/package-lock.json
- backend/package.json
- backend/src/functions/issueStatusListEntryHandler.ts
- backend/template.yaml
- backend/test/unit/issueStatusListEntry/issueStatusListEntry.test.ts
- backend/test/utils/mockRequest.ts
[DCMAW-12602](https://govukverify.atlassian.net/browse/DCMAW-12602)
Added error handling and tests for the following scenarios :
ClientId from clientRegistry doesnt match with the iss in the payload
Bad data in payload (cant parse json)
Not included issuer
Not included expiry
Not included kid
Kid doesnt match the kid from the jwks uri on the matching clientId
200: 
with following request:
```
{
"body": "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6ImNjMmMzNzM4LTAzZWMtNDIxNC1hNjVlLTdmMDQ2MWEzNGU3YiJ9.eyJpc3MiOiJhc0tXbnNqZUVKRVdqandTSHNJa3NJa3NJaEJlIiwiZXhwaXJlcyI6IjE3MzQ3MDk0OTMifQ.OlAm7TIfn-Qrs2yJvl6MDr9raiq_uZ6FV7WwaPz2CTuCuK-EkvsqM8139yjIiJq3pqeZk0S_23J-4SGBAkUXhA",
"path": "/issue",
"httpMethod": "POST",
"isBase64Encoded": true,
"pathParameters": {
"proxy": "/issue"
},
"headers": { …
```
> setup error handling for the issuestatuslistentry lambda

- backend/template.yaml
[DCMAW-12942](https://govukverify.atlassian.net/browse/DCMAW-12942)
Added backup tags to the following resources:
- List Configuration Bucket (Daily)
- Client Registry Bucket (Daily)
- Status List Bucket (Bihourly)
- Status List Table (Bihourly)
https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/4268589057/How+to+ensure+your+resources+are+backed+up
---
<details>
* Are the changes supported by sufficient …
> DCMAW-12942: added versioning to buckets and backup tagging

- backend/template.yaml
[DCMAW-12942](https://govukverify.atlassian.net/browse/DCMAW-12942)
Fix for jwksUri error saying its not defined by adding in the var for the higher envs
---
<details> …
> add jwksuri var to higher envs

- backend/package-lock.json
- backend/package.json
[DCMAW-13442](https://govukverify.atlassian.net/browse/DCMAW-13442)
Removed vulnerable dependency (smithy)
---
<details> …
> Removed the security vunerability smithy library

- backend/package-lock.json
- backend/package.json
- backend/src/common/logging/LogMessages.ts
- backend/src/common/types.ts
- backend/src/functions/issueStatusListEntryHandler.ts
- backend/template.yaml
- backend/test/unit/issueStatusListEntry/issueStatusListEntry.test.ts
[DCMAW-12604](https://govukverify.atlassian.net/browse/DCMAW-12604)
Add audit events (txma events) that are sent to the sqs queue
Added jwtVerify to enable public key verification (hardcoded but can be updated once we set up our key store)
Add tests for above
---
<details>
* Is anything being logged …
> Add audit txma events for issue status list entry. lambda

- backend/package-lock.json
- backend/package.json
- backend/src/common/types.ts
- backend/src/functions/issueStatusListEntryHandler.ts
- backend/template.yaml
- backend/test/unit/issueStatusListEntry/issueStatusListEntry.test.ts
[[DCMAW-11869](https://govukverify.atlassian.net/browse/DCMAW-11869)]
Added in logic to take messages of the correct sqs queue
Added in logic and tests to add a credential to the status list table.
Added in validation to the next available index - to see if it exists already and if it does it polls again.
---
<details>
* Are the changes supported by sufficient logging to help support, debug and analyse the …
> BE | Status List | IssueStatusListEntry | Add item to StatusListTable

- backend/template.yaml
update template yaml to include explicit log groups for fas and revoke lambdas
[[DCMAW-13074](https://govukverify.atlassian.net/browse/DCMAW-13074)]
I have added explicit log groups for the fas and revoke lambdas 
Explanation: We made this change as we need to explicitly create log groups for the lambdas to use within their metric filters
We name these lambda log groups the same way aws create default ones e.g. /aws/lambda/stack-name/function-name so it all gets connected. 
---
<details>
* Have API/end-to-end tests been updated to cover key new …
> update template yaml to include explicit log groups

- backend/template.yaml
Added Linear20PercentEvery1Minute Depoyment Configuration resource
[DCMAW-13404](https://govukverify.atlassian.net/browse/DCMAW-13404)
---
<details> …
> DCMAW-13404: Update Deployment Preference

- backend/template.yaml
Testing skip canary documentation
[DCMAW-13407](https://govukverify.atlassian.net/browse/DCMAW-13407)
---
<details> …
> DCMAW-13407: Skip Canary Test PR [skip canary]

- backend/template.yaml
[DCMAW-12595](https://govukverify.atlassian.net/browse/DCMAW-12595)
Updated permissions boundary for FAS to fix the `not authorized to perform: sqs:getqueueattributes` on the two AvailableSlots queues.
N/A, change scope too small to show evidence
N/A
---
<details>
* Is anything being logged that …
> DCMAW-12595: Update permissions boundary for FAS

- backend/template.yaml
[[DCMAW-14077](https://govukverify.atlassian.net/browse/DCMAW-14077)]
Update template to include permission for event source mapping to hopefully fix pipeline issue
---
<details>
* Does the code conform to our [values, …
> update template for permissions

- backend/template.yaml
N/A - chore
Changed the message code metric filter name for the issuer lambda to fix a pipeline build error
N/A - chore
N/A
---
<details> …
> DCMAW: Adjust issuer lambda metric filter name

- backend/package-lock.json
- backend/package.json
- backend/template.yaml
- backend/test/infra/application.test.ts
[DCMAW-14078](https://govukverify.atlassian.net/browse/DCMAW-14078)
Added an Event Bridge Pipe configured to listen to the Status List Table DynamoDB Stream, and send to the fifo Status Change Queue
[DCMAW-14078]: https://govukverify.atlassian.net/browse/DCMAW-14078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCMAW-14078: Add Event Bridge Pipe

- backend/src/functions/proxyHandler.ts
- backend/test/unit/proxy/proxy.test.ts
- backend/test/utils/mockProxyRequest.ts
[DCMAW-XXXX](https://govukverify.atlassian.net/browse/DCMAW-XXXX)
---
<details>
* Does the code conform to our [values, principles and practices](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3910271319/Values+Prin …
> Add unit testing for proxy handler
